name: 'Cursor Doctor'
description: 'Diagnose your Cursor .mdc and .cursorrules files — catch silent failures in CI'
author: 'nedcodes'

branding:
  icon: 'check-circle'
  color: 'orange'

inputs:
  directory:
    description: 'Directory to lint (default: repository root)'
    required: false
    default: '.'
  version:
    description: 'cursor-doctor version to use'
    required: false
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - name: Run cursor-doctor
      shell: bash
      run: |
        cd ${{ inputs.directory }}
        npx cursor-doctor@${{ inputs.version }} check
